### ISSUE TITLE
Feature Request: reading the _tail->item

### ISSUE THREAD

**Issue by agentgates** [EinarArnason/ArduinoQueue#10]
Hi,

Could you please add a feature that is similar to the front() function, but for reading the _tail-> item?

Something like this:
  T tail() {
    if ((_items_cnt == 0) || (_head == nullptr)) {
      return T();
    }
    T item = _tail->item;
    return item;
  }

Many thanks

PS: maybe renaming the front() to head() could also be useful for the sake of consistency. :)

**Comment by EinarArnason** [comment]
Commit <https://github.com/EinarArnason/ArduinoQueue/commit/6b0bdce4d30631e70a28090581163efa51288166> includes getTail function.
