### ISSUE TITLE
getHead() and getTail()  :  r/w-versions ?

### ISSUE THREAD

**Issue by martinzw** [EinarArnason/ArduinoQueue#13]
Hi Einar,

thanks a lot for your library!

I suggest to make the getHead() and getTail() functions return references or pointers.
e.g:
```
T & getHead() {
    if ((count == 0) || (head == nullptr)) {
      T tmp;    
      return &tmp;
    }

    T & item = head->item;
    return item;
  }
```
In my program I que up outgoing MIDI-messages and have to mark them first as acknowledged and later as answerded before i deque them.
So I need **write** access to the queued top message in the queue.
If i set the acknowledged flag in my message object at the queue's head i only modify the copy, not the message itself.

I had already changed it inside my installed library file - but the latest update changed it back.
So i would prefer it to be contained in the regular library - could be useful for others as well.
The pointer-version would also make the case with empty queue more consistent by returning a nullptr:

```
T * getHead() {
    if ((count == 0) || (head == nullptr)) {
          return nullptr;
    }

    return &(head->item);
  }

```

These different versions could of course co-exist in the library so the user can choose the right one for his use case.

Greetz,
Martin

**Comment by EinarArnason** [comment]
Any reason why you wouldn't queue pointers to objects which you can manipulate directly?
Like
```c++
queue.getHead()->ack = true;
```

**Comment by martinzw** [comment]
I would have to create the objects with "new" in this case, so need to use "delete" later on.

In  my program I create the objects statically while enqueing them:

`outqueue.enqueue( Outmessage(SysExMessage( (const byte[6]) { 0xF0, 0x7E, 0x7F, 0x06, 0x01, 0xF7}, 6 ), 1, true, true) );`

**Comment by EinarArnason** [comment]
I included getHeadPtr and getTailPtr functions in v1.2.3, so you can test them. I am hesitant to add a function for every case due to risk of clutter. Just want to make sure they are generic enough so it would make sense to include them instead of using inheritance.

**Comment by martinzw** [comment]
Thanks a lot, Einar.
The pointer version of "getHead()"  named  "getHeadPtr()" works in my program.
I can this way modify the top enqueded object and still enque static objects.
Perhaps you can add a note to this function in the Readme/Wiki?

btw. : 
Why was "front()" depreceated and renamed to "head()" first and then to "getHead()"?
Just a matter of naming taste?

**Comment by EinarArnason** [comment]
Thanks for the feedback. I'll take care of the paperwork soon.

The function renaming is for consistency and result of some refactoring. So
it's clearly understood what the functions do. There were others
contributing and there were mixed styles. From now on, one style will be
enforced.

Best regards,
Einar Arnason
