### ISSUE TITLE
Already exist queue.h in ESP8266

### ISSUE THREAD

**Issue by toruiwatani** [EinarArnason/ArduinoQueue#5]
queue.h already exists in compiler sys includes on ESP8266.
changed cpp/h names and updated examples

**Comment by EinarArnason** [comment]
I'm considering renaming everything to ArduinoQueue for consistency and to avoid conflict. But that would mean breaking change. If that's acceptable, I'll provide an update soon.

**Comment by EinarArnason** [comment]
Commit [2aa0292](https://github.com/EinarArnason/ArduinoQueue/commit/2aa02924653614bd3016ef990b4de0e09cdb0209) Adds uniform and unique naming for the header file and class.
