### ISSUE TITLE
performance & memory comparisons?

### ISSUE THREAD

**Issue by proddy** [EinarArnason/ArduinoQueue#7]
Hi there, firstly thanks for creating this library and making it public.

For one of my projects for an ESP8266 I need to make extensive use of queues (FIFO) for incoming and outgoing buffers. Now that the latest Arduino libraries for the ESP supports some of the C+11 stl libraries I switched from my homegrown solution to comparing `std::queue`, `std::deque` and `std::list`. 

I was wondering whether you had done any comparisons yourself, on speed or heap consumption?

**Comment by EinarArnason** [comment]
I don't have any real numbers to compare with. But what I can tell you is that this library is designed to have a very low overhead. The dynamic memory allocation is probably the biggest performance hit, but it relieves from having to decide a fixed memory size.

**Comment by EinarArnason** [comment]
Added a benchmark result to README
