### ISSUE TITLE
Question: What did I misunderstand?

### ISSUE THREAD

**Issue by Ezzue** [EinarArnason/ArduinoQueue#9]
Hello, 😊
I'm fairly new to programming and the only experience I have with it is through Arduino IDE.

My project consists of 6 LED's, 6 push-buttons working as initiators for the LED's and again 6 push-buttons that should reset the LED's to a LOW state. I use Arduino Mega 2560.

I want the first button pushed to be nr. 1 in a queue. If I push button nr. 5, it'll be nr. 1. in the queue. If push button nr. 5 is nr. 1 in the queue, that corresponding LED would be lit.

Then if I push-button nr. 3, that button would be nr. 2 in the queue. But if I push the reset button nr. 5, it would push nr. 5 out, at turn of the corresponding LED. Which would again put button nr. 5 as nr. 1 in the queue.

What have I misunderstood?

Thank you very much beforehand!

This is my code, which unfortunately dosen't work:

`#include "ArduinoQueue.h"

#define resetButton1 13
#define resetButton2 12
#define resetButton3 11
#define resetButton4 10
#define resetButton5 9
#define resetButton6 8

#define led1 23
#define led2 25
#define led3 27
#define led4 29
#define led5 31
#define led6 33

#define externalButton1 54
#define externalButton2 55
#define externalButton3 56
#define externalButton4 57
#define externalButton5 58
#define externalButton6 59

int extState1;
int extState2;
int extState3;
int extState4;
int extState5;
int extState6;

int resState1;
int resState2;
int resState3;
int resState4;
int resState5;
int resState6;

ArduinoQueue<int> intQueue(6);

int dq = intQueue.dequeue();
int qFront = intQueue.front();

void setup()
{
  pinMode(resetButton1, INPUT);
  pinMode(resetButton2, INPUT);
  pinMode(resetButton3, INPUT);
  pinMode(resetButton4, INPUT);
  pinMode(resetButton5, INPUT);
  pinMode(resetButton6, INPUT);

  pinMode(led1, OUTPUT);
  pinMode(led2, OUTPUT);
  pinMode(led3, OUTPUT);
  pinMode(led4, OUTPUT);
  pinMode(led5, OUTPUT);
  pinMode(led6, OUTPUT);

  pinMode(externalButton1, INPUT);
  pinMode(externalButton2, INPUT);
  pinMode(externalButton3, INPUT);
  pinMode(externalButton4, INPUT);
  pinMode(externalButton5, INPUT);
  pinMode(externalButton6, INPUT);

}

void loop()
{
  extState1 = analogRead(externalButton1);
  extState2 = analogRead(externalButton2);
  extState3 = analogRead(externalButton3);
  extState4 = analogRead(externalButton4);
  extState5 = analogRead(externalButton5);
  extState6 = analogRead(externalButton6);

  resState1 = digitalRead(resetButton1);
  resState2 = digitalRead(resetButton2);
  resState3 = digitalRead(resetButton3);
  resState4 = digitalRead(resetButton4);
  resState5 = digitalRead(resetButton5);
  resState6 = digitalRead(resetButton6);

// I have analogRead > 850 because these push-buttons are connected to the
// analog pins of the Arduino

  if (extState1 > 850)
  {
    intQueue.enqueue(1);
  }
  if (extState2 > 850)
  {
    intQueue.enqueue(2);
  }
  if (extState3 > 850)
  {
    intQueue.enqueue(3);
  }
  if (extState4 > 850)
  {
    intQueue.enqueue(4);
  }
  if (extState5 > 850)
  {
    intQueue.enqueue(5);
  }
  if (extState6 > 850)
  {
    intQueue.enqueue(6);
  }

  if (resState1 == HIGH)
  {
    dq = 1;
  }
  if (resState2 == HIGH)
  {
    dq = 2;
  }
  if (resState3 == HIGH)
  {
    dq = 3;
  }
  if (resState4 == HIGH)
  {
    dq = 4;
  }
  if (resState5 == HIGH)
  {
    dq = 5;
  }
  if (resState6 == HIGH)
  {
    dq = 6;
  }

  if (qFront == 1)
  {
    digitalWrite(led1, HIGH);
  }
  if (qFront == 2)
  {
    digitalWrite(led2, HIGH);
  }
  if (qFront == 3)
  {
    digitalWrite(led3, HIGH);
  }
  if (qFront == 4)
  {
    digitalWrite(led4, HIGH);
  }
  if (qFront == 5)
  {
    digitalWrite(led5, HIGH);
  }
  if (qFront == 6)
  {
    digitalWrite(led6, HIGH);
  }
  else
  {
    digitalWrite(led1, LOW);
    digitalWrite(led2, LOW);
    digitalWrite(led3, LOW);
    digitalWrite(led4, LOW);
    digitalWrite(led5, LOW);
    digitalWrite(led6, LOW);
  }
}`

**Comment by EinarArnason** [comment]
It is a template class, so you need to declare the type of data the queue contains.

change
```
ArduinoQueue intQueue(6);
```
to this
```
ArduinoQueue<int> intQueue(6);
```

**Comment by Ezzue** [comment]
Okay, I've done that now.
It unfortunately doesn't make it work.

But have I understood the other functions correct?
Like the dequeue and front?

Again, thank you for your time!

**Comment by Ezzue** [comment]
It does compile, btw!

**Comment by EinarArnason** [comment]
Enqueue pushes an item to the back of the queue.
Dequeue pops an item off the front the queue.
Front retrieves the item on the front of the queue without popping it off.

Beyond that, I suggest adapting some form of debugging method to trace and observe what your program is doing.

**Comment by Ezzue** [comment]
Hello, thank you for answering.

I have adapted a Serial feedback to debug my code, and it seems when I call for the front (or head) of the queue, it always returns 0, no matter what I enqueue.
- If i understand correctly, it'll put the number 4 in the queue if I write `ledQueue.enqueue(4);` ?
And if I then call the function `ledQueue.front();`, it should return said number 1?

**Comment by EinarArnason** [comment]
ledQueue.enqueue(4) puts 4 into the queue yes. ledQueue.front() would return 1 if it is the next number in line.

Can you provide a small code example of the problem you're having? Just a few lines where the problem occurs.

**Comment by Ezzue** [comment]
If I used `ledQueue.enqueue(4)` and then called the function `ledQueue.front()`, I should get the number 4, right? Like `ledQueue.front() = 4`. That is the what I based my following code on:

`  if (extState4 > 850)`
`  {`
`   Serial.println("Button 4 Pressed");`
`   ledQueue.enqueue(4);`
` }`

Button 4 is pressed. It would put button 4 in as the first in the queue?

I have integer the `int qFront = ledQueue.front();`

`  if (qFront == 4)`
`  {`
 `   digitalWrite(led4, HIGH);`
`  }`

I ask if button(4) is in front, and if it is, turn the corresponding led on.

And to reset, or dequeue, I would:
I have integer the `int dq = ledQueue.dequeue();`
`  if (resState4 == HIGH && qFront == 4)`
`  {`
`    Serial.println("Reset Button 4 Pressed");`
`    dq;`
And I would think if I just called the dequeue function, I would dequeue the first in the queue, correct?

Thank you!

**Comment by EinarArnason** [comment]
Well, let's see.  
Let's say the LED pin number is 4
```c++
int led4 = 4;
```
and the condition to add it to the queue is:
```c++
if (extState4 > 850) {
    ledQueue.enqueue(led4);
}
```
Now number 4 is the only int in the queue
```c++
if (ledQueue.front() == led4) // would equal true
```
Also, if the queue is only used to turn the LEDs on, you can do it like this:
```c++
while (!ledQueue.isEmpty()) {
    digitalWrite(ledQueue.dequeue(), HIGH);
}
```
Or if it is used to toggle the LEDs
```c++
while (!ledQueue.isEmpty()) {
    int ledPin = ledQueue.dequeue();
    digitalWrite(ledPin, !digitalRead(ledPin));
}
```
If the queue is empty and you call front or dequeue, a freshly instantiated object is returned as a dummy item. In this case it could be a random number. So checking ledQueue.isEmpty() before operations is good practice. 

I hope this sheds some light on this.

**Comment by Ezzue** [comment]
Hello again,
I forgot to get back to you but I just wanted to say thank you for your time and patience. 

I think I took a too big of a bite when I took this mission of getting this to work. I simply can't get my head around it!
Anyways, again, thank you!
